# Generated by Django 5.2.15 on 2026-08-23 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Customerdetails',
            },
        ),
        migrations.CreateModel(
            name='HotelProviders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('HotelName', models.CharField(max_length=100)),
                ('HotelType', models.IntegerField()),
                ('Price', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('msg', models.CharField(max_length=355)),
            ],
            options={
                'db_table': 'HotelProviders',
            },
        ),
        migrations.CreateModel(
            name='HotelImages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.BinaryField()),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.hotelproviders')),
            ],
            options={
                'db_table': 'HotelImages',
            },
        ),
    ]
