# Generated by Django 5.2.15 on 2026-08-24 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='requestData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('checkin', models.DateTimeField()),
                ('checkout', models.DateTimeField()),
            ],
            options={
                'db_table': 'requestData',
            },
        ),
    ]
