# Generated by Django 5.2.15 on 2026-08-24 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_requestdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestdata',
            name='checkin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='requestdata',
            name='checkout',
            field=models.DateField(),
        ),
    ]
