# Generated by Django 5.2.15 on 2026-08-24 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_alter_requestdata_checkin_alter_requestdata_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestdata',
            name='hotel_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
