# Generated by Django 5.2.15 on 2026-08-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_requestdata_hotel_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='history_data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hotelId', models.IntegerField()),
                ('cName', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('checkin', models.DateField()),
                ('checkout', models.DateField()),
                ('alloted_rooms', models.IntegerField()),
            ],
            options={
                'db_table': 'history_data',
            },
        ),
    ]
