# Generated by Django 5.2.15 on 2026-08-26 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_history_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='history_data',
            name='accepted_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
