# Generated by Django 5.2.15 on 2026-08-27 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_history_data_accepted_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelproviders',
            name='address',
            field=models.CharField(max_length=255),
        ),
    ]
